# Based on https://github.com/korfuri/bazel-travis

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - 
    packages:
      - gcc-4.9
      - g++-4.9
      - wget
      # Package list from http://bazel.io/docs/install.html
      - openjdk-7-jdk
      - openjdk-7-source
      - pkg-config
      - zip
      - zlib1g-dev

# Eventually, Bazel will have binary packages and we'll be able to
# just download a prebuilt distribution of Bazel. For now, build it
# from source every time.
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
# Bazel
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.1/bazel-0.2.1-installer-linux-x86_64.sh'
  - chmod +x bazel-0.2.1-installer-linux-x86_64.sh
  - ./bazel-0.2.1-installer-linux-x86_64.sh --user

script:
  - bazel build //control:ss_plant
  - bazel test //tests:plant_test --test_output=all
  - bazel test //tests:controller_test --test_output=all
