cc_test(
  name = "plant_test",
  deps = ["//third_party/eigen:eigen",
          "//third_party/googletest:gtest",
          "//control:ss_plant"],
  srcs = ["plant_test.cpp"]
  )

cc_test(
  name = "controller_test",
  deps = ["//third_party/eigen:eigen",
          "//third_party/googletest:gtest",
          "//control:ss_plant",
          "//control:ss_controller"],
  srcs = ["controller_test.cpp"]
  )
